module.exports = {
    name: 'Fabiano',
    id: 'UFBM5UFM5',
    courses: [
        'webapp-com-aspnet-core-2', 
        'aspnet-core-2-validacoes-seguranca', 
        'introducao-ao-mvc-com-asp-net-core', 
        'csharp-collections', 
        'csharp-collections-parte-2', 
        'csharp-parte-1-primeiros-passos', 
        'csharp-parte-2-introducao-orientacao-objetos', 
        'csharp-parte-3-heranca-interfaces-polimorfismo', 
        'csharp-parte-4-excecoes', 
        'csharp-biblioteca-dll-documentacao-nuget', 
        'csharp-string-regex-object', 
        'csharp-array-tipo-generico', 
        'csharp-list-lambda-linq', 
        'csharp-io', 
        'entity-framework-core', 
        'git', 
        'java-primeiros-passos', 
        'java-introducao-orientacao-objetos', 
        'linux-ubuntu', 
        'linux-ubuntu-processos', 
        'consultas-sql-server-2017', 
        'sql-com-sql-server-2017', 
        'vagrant-gerenciando-maquinas-virtuais', 
    ]
}