module.exports = {
    name: 'Felipe',
    id: 'UF9KPADEU',
    courses: [
        'posicione-elementos-com-flexbox',
        'projeto-carreira-front-end',
        'introducao-html-css',
        'avancando-html-css',
        'http-fundamentos',
        'javascript-es6-orientacao-a-objetos-parte-1',
        'javascript-es6-orientacao-a-objetos-parte-2',
        'javascript-programando-na-linguagem-web',
        'jquery-a-biblioteca-do-mercado-parte-2',
        'jquery-a-biblioteca-do-mercado',
        'logica-programacao-javascript-html',
        'logica-programacao-pratica-com-desenho-animacoes-em-jogo',
        'introducao-a-banco-de-dados-e-sql',
        'php-pdo-parte-1',
        'php-mysql-e-fundamentos-da-web',
        'php-mysql-e-fundamentos-da-web-parte-2',
        'php-oo-1',
        'php-oo-2',
        'php-pdo-parte-2',
        'php-avancado-orientacao-objetos',
        'php-orientacao-objetos',
        'sass',
        'pog',
        'web-design-responsivo',
    ]
}