module.exports = {
    name: 'Guilherme',
    id: 'UFC4KKERL',
    courses: [
        'android-sua-primeira-app-mobile',
        'http-fundamentos',
        'pitch',
        'java8-lambdas',
        'java-primeiros-passos',
        'java-introducao-orientacao-objetos',
        'java-heranca-interfaces-polimorfismo',
        'java-excecoes',
        'java-pacotes-e-java-lang',
        'java-util-lambdas',
        'java-trabalhando-com-io',
        'java-collections',
        'lean',
        'linux-ubuntu',
        'maven-build-do-zero-a-web',
        'oracle-sql',
        'ruby-on-rails-5',
        'servlets-fundamentos-programacao-web-java',
        'servlet-autenticacao-autorizacao-mvc',
        'introducao-a-uml',
    ]
}